// Menu Data with Ratings
const menuItems = [
    {
        id: 1,
        name: "Margherita Pizza",
        description: "Classic pizza with tomato sauce, mozzarella, and fresh basil",
        fullDescription: "Our signature Margherita pizza features a perfectly baked thin crust topped with rich tomato sauce, fresh mozzarella cheese, and aromatic basil leaves. A timeless classic that never goes out of style.",
        price: 450,
        category: "pizza",
        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop",
        rating: 4.5,
        reviews: 128,
        ingredients: ["Tomato Sauce", "Mozzarella Cheese", "Fresh Basil", "Olive Oil"]
    },
    {
        id: 2,
        name: "Pepperoni Pizza",
        description: "Traditional pizza with pepperoni and mozzarella cheese",
        fullDescription: "A crowd favorite! Generously topped with spicy pepperoni slices and gooey mozzarella cheese. Perfectly baked to golden perfection with a crispy crust.",
        price: 550,
        category: "pizza",
        image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&h=300&fit=crop",
        rating: 4.7,
        reviews: 203,
        ingredients: ["Pepperoni", "Mozzarella Cheese", "Tomato Sauce", "Oregano"]
    },
    {
        id: 3,
        name: "BBQ Chicken Pizza",
        description: "Grilled chicken, BBQ sauce, red onions, and mozzarella",
        fullDescription: "Tender grilled chicken pieces smothered in tangy BBQ sauce, topped with caramelized red onions and melted mozzarella. A perfect blend of sweet and savory flavors.",
        price: 650,
        category: "pizza",
        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=400&h=300&fit=crop",
        rating: 4.8,
        reviews: 156,
        ingredients: ["Grilled Chicken", "BBQ Sauce", "Red Onions", "Mozzarella Cheese"]
    },
    {
        id: 4,
        name: "Classic Burger",
        description: "Beef patty, lettuce, tomato, onion, and special sauce",
        fullDescription: "Our classic burger features a juicy 100% beef patty, fresh crisp lettuce, ripe tomatoes, onions, and our secret special sauce. Served in a toasted bun.",
        price: 350,
        category: "burger",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
        rating: 4.6,
        reviews: 189,
        ingredients: ["Beef Patty", "Lettuce", "Tomato", "Onion", "Special Sauce", "Bun"]
    },
    {
        id: 5,
        name: "Cheeseburger",
        description: "Beef patty with cheese, pickles, and our signature sauce",
        fullDescription: "Everything you love about our classic burger, plus melted cheese and tangy pickles. The perfect combination of flavors in every bite.",
        price: 380,
        category: "burger",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop",
        rating: 4.7,
        reviews: 167,
        ingredients: ["Beef Patty", "Cheese", "Pickles", "Lettuce", "Tomato", "Signature Sauce"]
    },
    {
        id: 6,
        name: "Bacon Burger",
        description: "Beef patty, crispy bacon, cheese, and BBQ sauce",
        fullDescription: "Indulge in this premium burger with crispy bacon strips, melted cheese, and smoky BBQ sauce. A meat lover's dream come true.",
        price: 450,
        category: "burger",
        image: "assets/Bacon Burger.jpeg",
        rating: 4.9,
        reviews: 142,
        ingredients: ["Beef Patty", "Crispy Bacon", "Cheese", "BBQ Sauce", "Lettuce", "Tomato"]
    },
    {
        id: 7,
        name: "Spaghetti Carbonara",
        description: "Creamy pasta with bacon, eggs, and parmesan cheese",
        fullDescription: "Authentic Italian pasta dish with a rich, creamy sauce made from eggs, crispy bacon, and freshly grated parmesan cheese. A true comfort food classic.",
        price: 520,
        category: "pasta",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop",
        rating: 4.6,
        reviews: 134,
        ingredients: ["Spaghetti", "Bacon", "Eggs", "Parmesan Cheese", "Black Pepper", "Cream"]
    },
    {
        id: 8,
        name: "Fettuccine Alfredo",
        description: "Rich and creamy pasta with parmesan and butter",
        fullDescription: "Silky smooth fettuccine noodles tossed in a decadent creamy Alfredo sauce made with butter, heavy cream, and parmesan cheese. Simple yet elegant.",
        price: 480,
        category: "pasta",
        image: "assets/Fettuccine Alfredo.jpeg",
        rating: 4.5,
        reviews: 98,
        ingredients: ["Fettuccine", "Butter", "Heavy Cream", "Parmesan Cheese", "Garlic"]
    },
    {
        id: 9,
        name: "Penne Arrabbiata",
        description: "Spicy tomato sauce with garlic and red chili peppers",
        fullDescription: "Bold and fiery pasta dish with penne pasta in a spicy tomato sauce infused with garlic and red chili peppers. For those who love a little heat!",
        price: 450,
        category: "pasta",
        image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400&h=300&fit=crop",
        rating: 4.4,
        reviews: 112,
        ingredients: ["Penne Pasta", "Tomato Sauce", "Garlic", "Red Chili", "Olive Oil", "Parsley"]
    },
    {
        id: 10,
        name: "Coca Cola",
        description: "Refreshing cola drink",
        fullDescription: "Ice-cold Coca Cola to quench your thirst. The perfect companion to any meal.",
        price: 80,
        category: "drinks",
        image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=300&fit=crop",
        rating: 4.2,
        reviews: 245,
        ingredients: ["Carbonated Water", "Sugar", "Natural Flavors"]
    },
    {
        id: 11,
        name: "Orange Juice",
        description: "Fresh squeezed orange juice",
        fullDescription: "100% fresh squeezed orange juice, packed with vitamin C. No added sugars or preservatives. Pure natural goodness.",
        price: 120,
        category: "drinks",
        image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
        rating: 4.6,
        reviews: 178,
        ingredients: ["Fresh Oranges"]
    },
    {
        id: 12,
        name: "Iced Coffee",
        description: "Cold brew coffee with ice",
        fullDescription: "Smooth and refreshing cold brew coffee served over ice. Perfect for coffee lovers who prefer their brew cold.",
        price: 150,
        category: "drinks",
        image: "assets/Iced Coffee.jpeg",
        rating: 4.7,
        reviews: 201,
        ingredients: ["Cold Brew Coffee", "Ice", "Milk (Optional)"]
    },
    {
        id: 13,
        name: "Chocolate Cake",
        description: "Rich chocolate cake with frosting",
        fullDescription: "Decadent chocolate cake with layers of rich chocolate sponge and creamy chocolate frosting. A chocolate lover's paradise.",
        price: 280,
        category: "dessert",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop",
        rating: 4.8,
        reviews: 165,
        ingredients: ["Chocolate Sponge", "Chocolate Frosting", "Cocoa Powder", "Butter"]
    },
    {
        id: 14,
        name: "Ice Cream Sundae",
        description: "Vanilla ice cream with chocolate sauce and toppings",
        fullDescription: "Creamy vanilla ice cream topped with rich chocolate sauce, whipped cream, and your choice of toppings. A classic dessert that never disappoints.",
        price: 220,
        category: "dessert",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop",
        rating: 4.5,
        reviews: 143,
        ingredients: ["Vanilla Ice Cream", "Chocolate Sauce", "Whipped Cream", "Cherry"]
    },
    {
        id: 15,
        name: "Cheesecake",
        description: "Creamy New York style cheesecake",
        fullDescription: "Classic New York style cheesecake with a buttery graham cracker crust and smooth, creamy filling. Topped with fresh berries.",
        price: 320,
        category: "dessert",
        image: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=400&h=300&fit=crop",
        rating: 4.9,
        reviews: 198,
        ingredients: ["Cream Cheese", "Graham Cracker Crust", "Sugar", "Fresh Berries"]
    },
    {
        id: 16,
        name: "Veggie Supreme Pizza",
        description: "Loaded with fresh vegetables and mozzarella cheese",
        fullDescription: "A vegetarian delight loaded with bell peppers, mushrooms, onions, olives, and sweet corn. Topped with generous amounts of mozzarella cheese on our signature thin crust.",
        price: 500,
        category: "pizza",
        image: "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=400&h=300&fit=crop",
        rating: 4.6,
        reviews: 187,
        ingredients: ["Bell Peppers", "Mushrooms", "Onions", "Olives", "Sweet Corn", "Mozzarella Cheese"]
    },
    {
        id: 17,
        name: "Hawaiian Pizza",
        description: "Ham, pineapple, and mozzarella on a crispy crust",
        fullDescription: "A tropical twist on classic pizza! Sweet pineapple chunks paired with savory ham and melted mozzarella. A perfect balance of sweet and salty flavors.",
        price: 580,
        category: "pizza",
        image: "assets/Hawaiian Pizza.jpeg",
        rating: 4.4,
        reviews: 134,
        ingredients: ["Ham", "Pineapple", "Mozzarella Cheese", "Tomato Sauce"]
    },
    {
        id: 18,
        name: "Mushroom Pizza",
        description: "Fresh mushrooms, garlic, and herbs on thin crust",
        fullDescription: "Earthy and aromatic pizza topped with fresh button mushrooms, roasted garlic, and a blend of Italian herbs. Simple yet incredibly flavorful.",
        price: 480,
        category: "pizza",
        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop",
        rating: 4.5,
        reviews: 156,
        ingredients: ["Button Mushrooms", "Garlic", "Italian Herbs", "Mozzarella Cheese", "Olive Oil"]
    },
    {
        id: 19,
        name: "Chicken Burger",
        description: "Grilled chicken patty with special sauce",
        fullDescription: "Tender grilled chicken patty served with fresh lettuce, tomato, and our signature spicy mayo sauce. A lighter alternative to beef burgers.",
        price: 380,
        category: "burger",
        image: "assets/Chicken Burger.jpeg",
        rating: 4.6,
        reviews: 203,
        ingredients: ["Grilled Chicken Patty", "Lettuce", "Tomato", "Spicy Mayo", "Bun"]
    },
    {
        id: 20,
        name: "Veggie Burger",
        description: "Plant-based patty with fresh vegetables",
        fullDescription: "A delicious plant-based burger patty made with vegetables and grains, topped with avocado, lettuce, tomato, and a tangy vegan sauce. Healthy and satisfying.",
        price: 320,
        category: "burger",
        image: "assets/Veggie Burger.jpeg",
        rating: 4.3,
        reviews: 178,
        ingredients: ["Veggie Patty", "Avocado", "Lettuce", "Tomato", "Vegan Sauce", "Bun"]
    },
    {
        id: 21,
        name: "Double Cheese Burger",
        description: "Two beef patties with double cheese",
        fullDescription: "For the ultimate burger experience! Two juicy beef patties, double cheese, pickles, onions, and our special sauce. Pure indulgence in every bite.",
        price: 520,
        category: "burger",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop",
        rating: 4.8,
        reviews: 167,
        ingredients: ["Double Beef Patty", "Double Cheese", "Pickles", "Onions", "Special Sauce", "Bun"]
    },
    {
        id: 22,
        name: "Spaghetti Bolognese",
        description: "Classic Italian pasta with meat sauce",
        fullDescription: "Traditional Italian comfort food! Al dente spaghetti topped with rich, slow-cooked meat sauce made from ground beef, tomatoes, and aromatic herbs.",
        price: 550,
        category: "pasta",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop",
        rating: 4.7,
        reviews: 189,
        ingredients: ["Spaghetti", "Ground Beef", "Tomato Sauce", "Onions", "Garlic", "Herbs"]
    },
    {
        id: 23,
        name: "Lasagna",
        description: "Layered pasta with meat, cheese, and tomato sauce",
        fullDescription: "Hearty Italian classic with layers of pasta, rich meat sauce, creamy béchamel, and melted cheese. Baked to perfection until golden and bubbly.",
        price: 620,
        category: "pasta",
        image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400&h=300&fit=crop",
        rating: 4.8,
        reviews: 145,
        ingredients: ["Lasagna Sheets", "Ground Meat", "Béchamel Sauce", "Mozzarella", "Parmesan", "Tomato Sauce"]
    },
    {
        id: 24,
        name: "Mac and Cheese",
        description: "Creamy macaroni with three types of cheese",
        fullDescription: "Ultra-creamy macaroni pasta smothered in a rich blend of cheddar, mozzarella, and parmesan cheeses. Baked until golden and crispy on top.",
        price: 420,
        category: "pasta",
        image: "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=400&h=300&fit=crop",
        rating: 4.6,
        reviews: 201,
        ingredients: ["Macaroni", "Cheddar Cheese", "Mozzarella", "Parmesan", "Cream", "Breadcrumbs"]
    },
    {
        id: 25,
        name: "Pepsi",
        description: "Classic cola soft drink",
        fullDescription: "Ice-cold Pepsi cola, the perfect fizzy refreshment to complement any meal.",
        price: 80,
        category: "drinks",
        image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=300&fit=crop",
        rating: 4.3,
        reviews: 198,
        ingredients: ["Carbonated Water", "Sugar", "Natural Flavors"]
    },
    {
        id: 26,
        name: "Mango Shake",
        description: "Fresh mango milkshake",
        fullDescription: "Creamy and refreshing mango milkshake made with fresh mangoes, milk, and a hint of vanilla. A tropical treat!",
        price: 140,
        category: "drinks",
        image: "assets/Mango juice.jpeg",
        rating: 4.7,
        reviews: 167,
        ingredients: ["Fresh Mango", "Milk", "Vanilla", "Ice"]
    },
    {
        id: 27,
        name: "Lemonade",
        description: "Fresh lemonade with mint",
        fullDescription: "Refreshing homemade lemonade with fresh lemon juice, sugar, and a sprig of mint. Perfect for hot days!",
        price: 100,
        category: "drinks",
        image: "assets/Lemonade.jpeg",
        rating: 4.5,
        reviews: 234,
        ingredients: ["Fresh Lemon Juice", "Sugar", "Water", "Mint Leaves", "Ice"]
    },
    {
        id: 28,
        name: "Hot Coffee",
        description: "Freshly brewed hot coffee",
        fullDescription: "Rich and aromatic hot coffee made from premium coffee beans. Served hot and fresh, perfect to start your day or enjoy after a meal.",
        price: 120,
        category: "drinks",
        image: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400&h=300&fit=crop",
        rating: 4.6,
        reviews: 189,
        ingredients: ["Coffee Beans", "Hot Water", "Sugar (Optional)", "Milk (Optional)"]
    },
    {
        id: 29,
        name: "Tiramisu",
        description: "Classic Italian coffee-flavored dessert",
        fullDescription: "Layers of coffee-soaked ladyfingers, mascarpone cheese, and cocoa powder. A sophisticated Italian dessert that melts in your mouth.",
        price: 350,
        category: "dessert",
        image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop",
        rating: 4.9,
        reviews: 178,
        ingredients: ["Ladyfingers", "Mascarpone Cheese", "Coffee", "Cocoa Powder", "Sugar"]
    },
    {
        id: 30,
        name: "Brownie Sundae",
        description: "Chocolate brownie with ice cream and toppings",
        fullDescription: "Warm chocolate brownie topped with vanilla ice cream, hot fudge, whipped cream, and a cherry. The ultimate dessert indulgence!",
        price: 280,
        category: "dessert",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop",
        rating: 4.8,
        reviews: 156,
        ingredients: ["Chocolate Brownie", "Vanilla Ice Cream", "Hot Fudge", "Whipped Cream", "Cherry"]
    },
    {
        id: 31,
        name: "Apple Pie",
        description: "Homemade apple pie with cinnamon",
        fullDescription: "Traditional apple pie with tender, spiced apple filling encased in a flaky, buttery crust. Served warm with a scoop of vanilla ice cream.",
        price: 250,
        category: "dessert",
        image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=400&h=300&fit=crop",
        rating: 4.6,
        reviews: 143,
        ingredients: ["Apples", "Cinnamon", "Sugar", "Butter", "Flour", "Vanilla Ice Cream"]
    },
    {
        id: 32,
        name: "Red Velvet Cake",
        description: "Moist red velvet cake with cream cheese frosting",
        fullDescription: "Beautifully moist red velvet cake with a hint of cocoa, topped with rich cream cheese frosting. A classic dessert that's both elegant and delicious.",
        price: 300,
        category: "dessert",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop",
        rating: 4.7,
        reviews: 167,
        ingredients: ["Red Velvet Cake", "Cream Cheese Frosting", "Cocoa Powder", "Butter"]
    },
    {
        id: 33,
        name: "Chicken Wings",
        description: "Crispy fried chicken wings with sauce",
        fullDescription: "Crispy, golden fried chicken wings tossed in your choice of sauce - buffalo, BBQ, or honey mustard. Served with celery sticks and blue cheese dip.",
        price: 380,
        category: "burger",
        image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=400&h=300&fit=crop",
        rating: 4.7,
        reviews: 198,
        ingredients: ["Chicken Wings", "Flour", "Spices", "Sauce", "Celery", "Blue Cheese Dip"]
    },
    {
        id: 34,
        name: "Caesar Salad",
        description: "Fresh romaine lettuce with Caesar dressing",
        fullDescription: "Crisp romaine lettuce tossed with creamy Caesar dressing, parmesan cheese, croutons, and anchovies. A classic salad that's both healthy and flavorful.",
        price: 280,
        category: "pasta",
        image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop",
        rating: 4.5,
        reviews: 134,
        ingredients: ["Romaine Lettuce", "Caesar Dressing", "Parmesan Cheese", "Croutons", "Anchovies"]
    },
    {
        id: 35,
        name: "Garlic Bread",
        description: "Toasted bread with garlic butter",
        fullDescription: "Crispy toasted bread slathered with garlic butter and herbs. The perfect side dish to complement any pasta or pizza meal.",
        price: 150,
        category: "pasta",
        image: "assets/Garlic Bread.jpeg",
        rating: 4.6,
        reviews: 245,
        ingredients: ["Bread", "Garlic", "Butter", "Parsley", "Parmesan Cheese"]
    }
];

